name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Pick deno version
        id: deno
        run: echo "version=$(grep deno .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ steps.deno.outputs.version }}

      - name: Check format
        run: deno fmt --check

      - name: Check lint
        run: deno lint

      - name: Run tests
        run: deno test --allow-net
